; /* /bitrix/js/intranet/structure.js?14161451382885*/
; /* /bitrix/js/intranet/core_planner.js?14161451382301*/
; /* /bitrix/js/intranet/outlook.js?14161451351225*/

; /* Start:"a:4:{s:4:"full";s:50:"/bitrix/js/intranet/core_planner.js?14161451382301";s:6:"source";s:35:"/bitrix/js/intranet/core_planner.js";s:3:"min";s:0:"";s:3:"map";s:0:"";}"*/
(function(){if(!!window.BX.CPlanner)return;var n=window.BX,t="/bitrix/tools/intranet_planner.php";n.planner_query=function(e,i,a,o,r){if(n.type.isFunction(a)){o=a;a={}}var s={method:"POST",dataType:"json",url:(e||t)+"?action="+i+"&site_id="+n.message("SITE_ID")+"&sessid="+n.bitrix_sessid(),data:n.ajax.prepareData(a),onsuccess:function(t){if(!!o){o(t,i)}n.onCustomEvent("onPlannerQueryResult",[t,i])},onfailure:function(t,e){if(e&&e.type=="json_failure"){new n.PopupWindow("planner_failure_"+Math.random(),null,{content:n.create("DIV",{style:{width:"300px"},html:n.message("JS_CORE_PL_ERROR")+"<br /><br /><small>"+n.util.strip_tags(e.data)+"</small>"}),buttons:[new n.PopupWindowButton({text:n.message("JS_CORE_WINDOW_CLOSE"),className:"popup-window-button-decline",events:{click:function(){this.popupWindow.close()}}})]}).show()}}};return n.ajax(s)};n.CPlanner=function(t){this.DATA=t;this.DIV=null;this.DIV_ADDITIONAL=null;this.WND=null;n.addCustomEvent("onGlobalPlannerDataRecieved",n.delegate(this.onPlannerBroadcastRecieved,this));n.onCustomEvent("onPlannerInit",[this,this.DATA])};n.CPlanner.prototype.onPlannerBroadcastRecieved=function(t){this.DATA=t;n.onCustomEvent(this,"onPlannerDataRecieved",[this,this.DATA])};n.CPlanner.prototype.draw=function(){if(!this.DIV){this.DIV=n.create("DIV",{props:{className:"bx-planner-content"}})}n.onGlobalCustomEvent("onGlobalPlannerDataRecieved",[this.DATA]);return this.DIV};n.CPlanner.prototype.drawAdditional=function(){if(!this.DIV_ADDITIONAL){this.DIV_ADDITIONAL=n.create("DIV",{style:{minHeight:0}})}return this.DIV_ADDITIONAL};n.CPlanner.prototype.addBlock=function(t,e){if(!t||!n.type.isElementNode(t)){return}t.bxsort=parseInt(e)||100;if(!!t.parentNode){t.parentNode.removeChild(t)}var i=this.DIV.firstChild;while(i){if(i==t)break;if(!!i.bxsort&&i.bxsort>t.bxsort){this.DIV.insertBefore(t,i);break}i=i.nextSibling}if(!t.parentNode||!n.type.isElementNode(t.parentNode)){this.DIV.appendChild(t)}};n.CPlanner.prototype.addAdditional=function(n){this.drawAdditional().appendChild(n)};n.CPlanner.prototype.update=function(n){if(!!n){this.DATA=n;this.draw()}else{this.query("update")}};n.CPlanner.prototype.query=function(e,i){return n.planner_query(t,e,i,n.proxy(this.update,this))};n.CPlanner.query=function(e,i){return n.planner_query(t,e,i)}})();
/* End */
;
; /* Start:"a:4:{s:4:"full";s:45:"/bitrix/js/intranet/outlook.js?14161451351225";s:6:"source";s:30:"/bitrix/js/intranet/outlook.js";s:3:"min";s:0:"";s:3:"map";s:0:"";}"*/
var jsOutlookUtils={encode:function(e){var t,o=e.length,i,l,s="",n=false,r="&\\[]|";for(t=0;t<o;t++){i=e.charAt(t);l=i.charCodeAt(0);if(n&&l<=127){s+="]";n=false}if(!n&&l>127){s+="[";n=true}if(r.indexOf(i)>=0)s+="|";if(l>=97&&l<=122||l>=65&&l<=90||l>=48&&l<=57)s+=i;else if(l<=15)s+="%0"+l.toString(16).toUpperCase();else if(l<=127)s+="%"+l.toString(16).toUpperCase();else if(l<=255)s+="00"+l.toString(16).toUpperCase();else if(l<=4095)s+="0"+l.toString(16).toUpperCase();else s+=l.toString(16).toUpperCase()}if(n)s+="]";return s},Sync:function(e,t,o,i,l,s,n,r){var a=500,c=20,f=window.location.host;if(!!n){f=f.replace(/:\d+/,"")+":"+n}t=window.location.protocol+"//"+f+t;s=s.replace(/{/g,"%7B").replace(/}/g,"%7D").replace(/-/g,"%2D");var d="stssync://sts/?ver=1.1"+"&type="+e+"&cmd=add-folder"+"&base-url="+jsOutlookUtils.encode(t)+"&list-url="+jsOutlookUtils.encode(o)+"&guid="+s;var g="&site-name="+jsOutlookUtils.encode(i)+"&list-name="+jsOutlookUtils.encode(l);if(d.length+g.length>a&&(i.length>c||l.length>c)){if(i.length>c)i=i.substring(0,c-1)+"...";if(l.length>c)l=l.substring(0,c-1)+"...";g="&site-name="+jsOutlookUtils.encode(i)+"&list-name="+jsOutlookUtils.encode(l)}d+=g;try{window.location.href=d}catch(p){}}};
/* End */
;
; /* Start:"a:4:{s:4:"full";s:47:"/bitrix/js/intranet/structure.js?14161451382885";s:6:"source";s:32:"/bitrix/js/intranet/structure.js";s:3:"min";s:0:"";s:3:"map";s:0:"";}"*/
(function(){if(!!BX.IntranetStructure)return;BX.IntranetStructure={bInit:false,popup:null,arParams:{}};BX.IntranetStructure.Init=function(t){if(t)BX.IntranetStructure.arParams=t;if(BX.IntranetStructure.bInit)return;BX.IntranetStructure.bInit=true;BX.ready(BX.delegate(function(){BX.IntranetStructure.popup=BX.PopupWindowManager.create("BXStructure",null,{autoHide:false,zIndex:0,offsetLeft:0,offsetTop:0,draggable:{restrict:true},closeByEsc:true,titleBar:{content:BX.create("span",{html:BX.message("INTR_STRUCTURE_TITLE"+(t["UF_DEPARTMENT_ID"]>0?"_EDIT":""))})},closeIcon:{right:"12px",top:"10px"},buttons:[new BX.PopupWindowButton({text:BX.message("INTR_STRUCTURE_BUTTON"),className:"popup-window-button-accept",events:{click:function(){var t=BX("STRUCTURE_FORM");handler=BX.delegate(function(t){if(t=="close"){BX.IntranetStructure.popup.close();if(window.BXSTRUCTURECALLBACK)window.BXSTRUCTURECALLBACK.apply(BX.IntranetStructure.popup,[t]);else BX.reload()}else if(/^error:/.test(t)){var e=BX.create("DIV",{html:'<div class="webform-round-corners webform-error-block" style="margin-top:5px" id="error">												<div class="webform-corners-top"><div class="webform-left-corner"></div><div class="webform-right-corner"></div></div>												<div class="webform-content">													<ul class="webform-error-list">'+t.substring(6,t.length)+'</ul>												</div>												<div class="webform-corners-bottom"><div class="webform-left-corner"></div><div class="webform-right-corner"></div></div>											</div>'});if(BX.findChild(BX.IntranetStructure.popup.contentContainer,{className:"webform-error-block"},true)){BX.IntranetStructure.popup.contentContainer.replaceChild(e,BX.IntranetStructure.popup.contentContainer.firstChild)}else{BX.IntranetStructure.popup.contentContainer.insertBefore(e,BX.IntranetStructure.popup.contentContainer.firstChild)}}else{BX.IntranetStructure.popup.setContent(t);if(window.BXSTRUCTURECALLBACK)window.BXSTRUCTURECALLBACK.apply(BX.IntranetStructure.popup,[t])}});if(t){if(!t.reload){BX.ajax.submit(t,handler)}else{BX.ajax.get(t.action,handler)}}}}}),new BX.PopupWindowButtonLink({text:BX.message("INTR_CLOSE_BUTTON"),className:"popup-window-button-link-cancel",events:{click:function(){this.popupWindow.close()}}})],content:'<div style="width:450px;height:230px"></div>',events:{onAfterPopupShow:function(){this.setContent('<div style="width:450px;height:230px" id="intr_struct_load">'+BX.message("INTR_LOADING")+"</div>");BX.ajax.post("/bitrix/tools/intranet_structure.php",{lang:BX.message("LANGUAGE_ID"),site_id:BX.message("SITE_ID")||"",arParams:BX.IntranetStructure.arParams},BX.delegate(function(t){this.setContent(t)},this))}}})},this))};BX.IntranetStructure.ShowForm=function(t){BX.IntranetStructure.Init(t);BX.IntranetStructure.popup.params.zIndex=BX.WindowManager?BX.WindowManager.GetZIndex():0;BX.IntranetStructure.popup.show()}})();
/* End */
;